// USER ACTIONS
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_CREATED = 'USER_CREATED';

//TODO ACTIONS
export const TODO_LOADING = 'TODO_LOADING';
export const TODO_LOADED = 'TODO_LOADED';
export const TODO_ADDED = 'TODO_ADDED';
export const TODO_UPDATED = 'TODO_UPDATED';
export const TODO_DELETED = 'TODO_DELETED';